version: '3.8'
services:
  # Локальная БД сервиса
  task-tracker-db:
    image: postgres
    container_name: task-tracker-db
    environment:
      POSTGRES_USER: task_tracker_db_admin
      POSTGRES_PASSWORD: task_tracker_db_admin
    ports:
      - 5433:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

